spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
JWT_SECRET: "JWT_SECRET=U2FsdGVkX1+4QnN1ZmY0NndpbmFoZXJlaXRoZWlwamRvZWpkb2VramRmZGZlZnRl"
JWT_EXPIRATION: 86400000



